<?php

/**
 * Implementation of hook_uuid_features_default_terms().
 */
function piropublic_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'uuid' => 'f76d7a2e-ce94-11e0-b44a-9f094f73513e',
    'name' => '3rd Parties',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76de776-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Civil Liberties',
    'description' => '',
    'weight' => '4',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e1482-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Congress',
    'description' => '',
    'weight' => '6',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e6498-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Economy',
    'description' => '',
    'weight' => '10',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e7a4e-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Education',
    'description' => '',
    'weight' => '11',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76ea338-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Ethics',
    'description' => '',
    'weight' => '13',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76eb71c-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Executive Power',
    'description' => '',
    'weight' => '14',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76edfab-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Finance',
    'description' => '',
    'weight' => '16',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76ef2df-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Foreign Policy',
    'description' => '',
    'weight' => '17',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f068d-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Free Markets',
    'description' => '',
    'weight' => '18',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f1a09-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Globalism',
    'description' => '',
    'weight' => '19',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f2ecf-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Grassroots',
    'description' => '',
    'weight' => '20',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f42a3-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Health',
    'description' => '',
    'weight' => '21',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f74dc-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Law',
    'description' => '',
    'weight' => '24',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f9b25-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Miscellany',
    'description' => '',
    'weight' => '26',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76fac22-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Monetary Policy',
    'description' => '',
    'weight' => '27',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76fb8a4-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Philosophy',
    'description' => '',
    'weight' => '28',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f7700275-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Social Issues',
    'description' => '',
    'weight' => '34',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f7700e35-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Socialism',
    'description' => '',
    'weight' => '35',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f770260e-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Trade',
    'description' => '',
    'weight' => '37',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f77031f7-ce94-11e0-b44a-9f094f73513e',
    'name' => 'US Constitution',
    'description' => '',
    'weight' => '38',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f7704adf-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Voting',
    'description' => '',
    'weight' => '40',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f770588c-ce94-11e0-b44a-9f094f73513e',
    'name' => 'War and Military',
    'description' => '',
    'weight' => '41',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  return $terms;
}
