<?php

/**
 * Implementation of hook_uuid_features_default_terms().
 */
function piropublic_about_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'uuid' => 'fa46b1ee-9446-11e0-88ba-e0e2cd5d67f0',
    'name' => 'About Our Organization',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => 'fa4251dd-9446-11e0-88ba-e0e2cd5d67f0',
  );
  $terms[] = array(
    'uuid' => 'fa46c78d-9446-11e0-88ba-e0e2cd5d67f0',
    'name' => 'Blog',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => 'fa4251dd-9446-11e0-88ba-e0e2cd5d67f0',
  );
  $terms[] = array(
    'uuid' => 'fa46ef34-9446-11e0-88ba-e0e2cd5d67f0',
    'name' => 'General Troubleshooting',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => 'fa4251dd-9446-11e0-88ba-e0e2cd5d67f0',
  );
  $terms[] = array(
    'uuid' => 'fa471a7a-9446-11e0-88ba-e0e2cd5d67f0',
    'name' => 'Miscellaneous',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => 'fa4251dd-9446-11e0-88ba-e0e2cd5d67f0',
  );
  return $terms;
}
